function WordLists_1 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  WORDLISTS_1 = IMPORTFILE1(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  WORDLISTS_1 = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  WORDLISTS_1 = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  WordLists_1 = importfile1("C:\Users\ricca\OneDrive\PJ - 02 - TOKALAB_fusion\01 - github repositories\Games\FusionTaboo\Word Lists.xlsx", "List 1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Nov-2025 11:17:28

%% Input handling

% If no sheet is specified, read from List 1
if nargin == 1 || isempty(sheetName)
    sheetName = "List 1";
end

% If row start and end points are not specified, define defaults
lastRowOfDataIdx = 0;
if nargin <= 2
    dataLines = [2, Inf];
    lastRowOfDataIdx = 1;
elseif dataLines(end,2) >= Inf
    lastRowOfDataIdx = size(dataLines, 1);
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
if lastRowOfDataIdx == 1
    opts.DataRange = "A" + dataLines(1, 1);
else
    opts.DataRange = "A" + dataLines(1, 1) + ":G" + dataLines(1, 2);
end

% Specify column names and types
opts.VariableNames = ["Word", "Description", "Forbidden1", "Forbidden2", "Forbidden3", "Forbidden4", "Forbidden5"];
opts.VariableTypes = ["string", "categorical", "string", "string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["Word", "Forbidden1", "Forbidden2", "Forbidden3", "Forbidden4", "Forbidden5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Word", "Description", "Forbidden1", "Forbidden2", "Forbidden3", "Forbidden4", "Forbidden5"], "EmptyFieldRule", "auto");

% Import the data
WordLists_1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    if idx == lastRowOfDataIdx
        opts.DataRange = "A" + dataLines(idx, 1);
    else
        opts.DataRange = "A" + dataLines(idx, 1) + ":G" + dataLines(idx, 2);
    end
    tb = readtable(workbookFile, opts, "UseExcel", false);
    WordLists_1 = [WordLists_1; tb]; %#ok<AGROW>
end

end